languageCode = "fr"
DefaultContentLanguage = "fr"

baseURL = "datalabsite"
relativeurls = true

enableEmoji = true

publishDir = "www"
title = "Datalab Bordeaux Métropole"
theme = "hugo-xmin"

googleAnalytics = ""
disqusShortname = ""

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Nos applications"
    url = "/apps/"
    weight = 2

[[menu.main]]
    name = "Nos articles"
    url = "/post/"
    weight = 3

[[menu.main]]
    name = "Nos outils"
    url = "/tools/"
    weight = 4


[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true


[params]
    footer = "Copyright &copy; [Bordeaux Métropole](https://www.bordeaux-metropole.fr/) 2019 -- 2019 Tous droits réservés"
    author = "Yohann Mansiaux"
    dateFormat = "2006/01/02"
    description = "Un site de présentation du datalab"

    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

[params.features]
    enable = true

[params.logo]
    url = "LogoDataLab.png"
    width = 50
    height = 50
    alt = "Logo"

[params.widgets]
    categories = true
    tags = true
[params.carousel]
    enable = true
[params.recent_posts]
    enable = true

